# Generated by Django 4.1 on 2022-09-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='estimatedTimeOfDeparture',
            field=models.TimeField(default=False),
        ),
    ]
